parameters:
    demontpx_parsedown.breaks_enabled: false
    demontpx_parsedown.markup_escaped: false
    demontpx_parsedown.urls_linked: true

services:
    demontpx_parsedown.parsedown:
        class: Demontpx\ParsedownBundle\Parsedown
        calls:
            - [setBreaksEnabled, [%demontpx_parsedown.breaks_enabled%]]
            - [setMarkupEscaped, [%demontpx_parsedown.markup_escaped%]]
            - [setUrlsLinked, [%demontpx_parsedown.urls_linked%]]

    demontpx_parsedown.controller:
        class: Demontpx\ParsedownBundle\Controller\ParsedownController
        arguments:
            - "@demontpx_parsedown.parsedown"

    demontpx_parsedown.twig.extension.parsedown:
        class: Demontpx\ParsedownBundle\Twig\ParsedownExtension
        arguments:
            - "@demontpx_parsedown.parsedown"
        tags:
            - { name: twig.extension }
